name: PVP-Wild
version: 1.0.0
api-version: '1.16'
main: com.noobnuby.plugin.Main
description: Get items and fight in the Minecraft!
website: https://me.noobnuby.com
author: noobnuby
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.9.0
  - io.github.monun:kommand:1.2.1

commands:
  start:
  chat:
  top: